name: Deploy client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      
  # pull_request:
  #   branches:
  #     - master
  #   paths:
  #     - 'client/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install client dependencies
        run: cd client && npm i

      - name: Build Client
        run: cd client && CI=false npm run build
      
      - name: Deploy Client
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: client
