name: Deploy app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Install common dependencies
        run: npm install
        
#       - name: Install server dependencies
#         run: cd server && npm install
        
#       - name: Install client dependencies
#         run: cd client && npm install
        
      
      - uses: ActionwareIO/branch-push-action@action
        with:
          branch: server
          files: |
            ./server/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

