name: Deploy app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
#       - name: Install common dependencies
#         run: npm install
        
#       - name: Install server dependencies
#         run: cd server && npm install
        
#       - name: Install client dependencies
#         run: cd client && npm install

      - name: Build Client
        run: cd client && npm build
      
      - name: Deploy Client
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: client

      - name: Deploy Server
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./server
          publish_branch: server
