name: Deploy server

on:
  push:
    paths:
      - 'server/**'
      
  pull_request:
    paths:
      - 'server/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install server dependencies
        run: cd server && npm ci
        
      - name: Deploy Server
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./server
          publish_branch: server
